<?php
//000000000010a:7:{i:0;a:13:{s:8:"goods_id";s:1:"2";s:10:"goods_name";s:15:"诺基亚N855qq";s:12:"goods_weight";s:3:"111";s:11:"goods_price";s:7:"1000.00";s:12:"goods_number";s:3:"122";s:17:"goods_category_id";s:1:"3";s:14:"goods_brand_id";s:1:"1";s:15:"goods_introduce";s:42240:"&lt;p&gt;诺基亚N85参数&lt;/p&gt;
&lt;div&gt; &lt;/div&gt;
&lt;div&gt;
&lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
    &lt;tbody&gt;
        &lt;tr&gt;
            &lt;td bgcolor=&quot;#f1f7fc&quot; colspan=&quot;2&quot;&gt;
            &lt;p&gt;&lt;b&gt;基本参数&lt;/b&gt;&lt;/p&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;手机昵称&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;N85&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;上市日期&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;2008年10月&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;手机类型&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;3G手机；拍照手机；智能手机&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;手机制式&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;GSM&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;支持频段&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;GSM850/900/1800/1900MHz&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;数据传输&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;GPRS、EDGE&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;屏幕材质&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;AMOLED&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;屏幕色彩&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;1600万色&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;主屏尺寸&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;2.6英寸&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;主屏参数&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;QVGA 320×240像素&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;铃音描述&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;可选MP3、WAV、AAC或和弦Midi铃声等格式&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;操作系统&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;Symbian OS v9.3操作系统与S60 v3.2平台的组合&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;机身内存&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;74MB 内部动态存储空间&lt;br /&gt;
            78MB 内置NAND闪存&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;存储卡&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;支持MicroSD(T-Flash)卡扩展最大至8GB&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;电池规格&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;1200毫安时锂电池&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;标配&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;诺基亚 N85&lt;br /&gt;
            诺基亚电池（BL-5K）&lt;br /&gt;
            诺基亚旅行充电器（AC-10）&lt;br /&gt;
            诺基亚视频数据线（CA-75U）&lt;br /&gt;
            诺基亚数据线（CA-101）&lt;br /&gt;
            诺基亚音乐耳机（HS-45、AD-54）&lt;br /&gt;
            诺基亚 8 GB microSD 卡（MU-43）&lt;br /&gt;
            《用户手册》&lt;br /&gt;
            《快速入门》&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;理论通话时间&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;6.9 小时&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;理论待机时间&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;363 小时&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td bgcolor=&quot;#f1f7fc&quot; colspan=&quot;2&quot;&gt;
            &lt;p&gt;&lt;b&gt;产品外形&lt;/b&gt;&lt;/p&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;外观设计&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;双向滑盖&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;产品尺寸&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;103×50×16mm&lt;br /&gt;
            体积：76 立方厘米&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;手机重量&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;128克&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;产品天线&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;内置&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td bgcolor=&quot;#f1f7fc&quot; colspan=&quot;2&quot;&gt;
            &lt;p&gt;&lt;b&gt;拍照功能&lt;/b&gt;&lt;/p&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;550&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot; style=&quot;padding: 8px 0px;&quot; colspan=&quot;2&quot;&gt;
            &lt;table cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;left&quot;&gt;
                &lt;tbody&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;定时器&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt; &lt;/td&gt;
                    &lt;/tr&gt;
                &lt;/tbody&gt;
            &lt;/table&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;摄像头&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;内置&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;摄像头像素&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;500万像素&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;连拍功能&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;支持&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;LED闪光灯&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;双LED 闪光灯&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;数码变焦&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;20 倍数码变焦&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;拍摄模式&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;静止、连拍、自动定时器、摄像&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;照片特效&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;正常、怀旧、黑白、负片、逼真&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;拍照描述&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;支持最大2592×1944分辨率照片拍摄&lt;br /&gt;
            支持JPEG、Exif格式&lt;br /&gt;
            白平衡模式：自动、阳光、阴天、白炽灯、荧光灯&lt;br /&gt;
            感光度模式：高、中、低、自动&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;视频拍摄&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;最高支持640 x 480 像素（VGA）、30 帧/秒&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td bgcolor=&quot;#f1f7fc&quot; colspan=&quot;2&quot;&gt;
            &lt;p&gt;&lt;b&gt;娱乐功能&lt;/b&gt;&lt;/p&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;550&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot; style=&quot;padding: 8px 0px;&quot; colspan=&quot;2&quot;&gt;
            &lt;table cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;left&quot;&gt;
                &lt;tbody&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;收音机&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;TV-OUT&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;录音功能&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;电子书&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt; &lt;/td&gt;
                    &lt;/tr&gt;
                &lt;/tbody&gt;
            &lt;/table&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;视频播放&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;内置RealPlayer播放器, 支持MPEG4、H.264/AVC、H.263/3GP、RealVideo等视频格式全屏播放&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;音乐播放&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;内置播放器, 支持mp3、.wma、.aac、eAAC、eAAC+格式&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;游戏&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;内置&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;Java功能&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;支持Java MIDP 2.0 CLDC 1.1&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;Flash功能&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;第3.0版Flash lite播放器&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td bgcolor=&quot;#f1f7fc&quot; colspan=&quot;2&quot;&gt;
            &lt;p&gt;&lt;b&gt;数据功能&lt;/b&gt;&lt;/p&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;550&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot; style=&quot;padding: 8px 0px;&quot; colspan=&quot;2&quot;&gt;
            &lt;table cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;left&quot;&gt;
                &lt;tbody&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;蓝牙功能&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt; &lt;/td&gt;
                    &lt;/tr&gt;
                &lt;/tbody&gt;
            &lt;/table&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;数据线接口&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;USB数据线 3.5mm立体声耳机插孔&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td bgcolor=&quot;#f1f7fc&quot; colspan=&quot;2&quot;&gt;
            &lt;p&gt;&lt;b&gt;基本功能&lt;/b&gt;&lt;/p&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;550&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot; style=&quot;padding: 8px 0px;&quot; colspan=&quot;2&quot;&gt;
            &lt;table cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;left&quot;&gt;
                &lt;tbody&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;短信(SMS)&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;彩信(MMS)&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;免提通话&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;情景模式&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;闹钟功能&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                    &lt;/tr&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;日历功能&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt; &lt;/td&gt;
                    &lt;/tr&gt;
                &lt;/tbody&gt;
            &lt;/table&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;输入方式&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;键盘&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;通话记录&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;未接来电+已接来电+已拨电话记录&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;100&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot;&gt;通讯录&lt;/td&gt;
            &lt;td width=&quot;450&quot; bgcolor=&quot;#ffffff&quot;&gt;S60标准化名片式通讯录&lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td bgcolor=&quot;#f1f7fc&quot; colspan=&quot;2&quot;&gt;
            &lt;p&gt;&lt;b&gt;网络功能&lt;/b&gt;&lt;/p&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;550&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot; style=&quot;padding: 8px 0px;&quot; colspan=&quot;2&quot;&gt;
            &lt;table cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;left&quot;&gt;
                &lt;tbody&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;电子邮件&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;WWW浏览器&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;WAP浏览器&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt; &lt;/td&gt;
                    &lt;/tr&gt;
                &lt;/tbody&gt;
            &lt;/table&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td bgcolor=&quot;#f1f7fc&quot; colspan=&quot;2&quot;&gt;
            &lt;p&gt;&lt;b&gt;商务功能&lt;/b&gt;&lt;/p&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;550&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot; style=&quot;padding: 8px 0px;&quot; colspan=&quot;2&quot;&gt;
            &lt;table cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;left&quot;&gt;
                &lt;tbody&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;飞行模式&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;语音拨号&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;备忘录&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;日程表&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;世界时间&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                    &lt;/tr&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt; &lt;/td&gt;
                    &lt;/tr&gt;
                &lt;/tbody&gt;
            &lt;/table&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td bgcolor=&quot;#f1f7fc&quot; colspan=&quot;2&quot;&gt;
            &lt;p&gt;&lt;b&gt;其他功能&lt;/b&gt;&lt;/p&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
        &lt;tr&gt;
            &lt;td width=&quot;550&quot; valign=&quot;center&quot; bgcolor=&quot;#ffffff&quot; align=&quot;left&quot; style=&quot;padding: 8px 0px;&quot; colspan=&quot;2&quot;&gt;
            &lt;table cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; align=&quot;left&quot;&gt;
                &lt;tbody&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;GPS功能&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;电子词典&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;待机图片&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;计算器&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;来电铃声识别&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                    &lt;/tr&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;来电图片识别&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;来电防火墙&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;动画屏保&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;图形菜单&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;秒表&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                    &lt;/tr&gt;
                    &lt;tr&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; bgcolor=&quot;#c5d7ed&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; bgcolor=&quot;#f1f7fc&quot; align=&quot;middle&quot; style=&quot;padding: 2px; font-weight: bold;&quot;&gt;单位换算&lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                        &lt;td width=&quot;100&quot; style=&quot;padding: 5px 0px 5px 10px;&quot;&gt;
                        &lt;table width=&quot;100%&quot; cellspacing=&quot;1&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;&gt;
                            &lt;tbody&gt;
                                &lt;tr&gt;
                                    &lt;td width=&quot;100%&quot; align=&quot;middle&quot; style=&quot;padding: 2px; float: none;&quot;&gt; &lt;/td&gt;
                                &lt;/tr&gt;
                            &lt;/tbody&gt;
                        &lt;/table&gt;
                        &lt;/td&gt;
                    &lt;/tr&gt;
                &lt;/tbody&gt;
            &lt;/table&gt;
            &lt;/td&gt;
        &lt;/tr&gt;
    &lt;/tbody&gt;
&lt;/table&gt;
&lt;/div&gt;
&lt;p&gt; &lt;/p&gt;";s:13:"goods_big_img";s:22:"32_G_1242110760868.jpg";s:15:"goods_small_img";s:52:"images/200905/thumb_img/32_thumb_G_1242110760196.jpg";s:17:"goods_create_time";s:10:"1242110760";s:15:"goods_last_time";s:10:"1376313168";s:3:"abc";s:0:"";}i:1;a:13:{s:8:"goods_id";s:1:"4";s:10:"goods_name";s:27:"诺基亚N85原装充电器";s:12:"goods_weight";s:4:"3333";s:11:"goods_price";s:6:"111.00";s:12:"goods_number";s:3:"222";s:17:"goods_category_id";s:1:"8";s:14:"goods_brand_id";s:1:"1";s:15:"goods_introduce";s:9:"asdasdasd";s:13:"goods_big_img";s:21:"4_G_1241422402722.jpg";s:15:"goods_small_img";s:51:"images/200905/thumb_img/4_thumb_G_1241422402467.jpg";s:17:"goods_create_time";s:10:"1241422402";s:15:"goods_last_time";s:1:"0";s:3:"abc";s:0:"";}i:2;a:13:{s:8:"goods_id";s:1:"6";s:10:"goods_name";s:15:"胜创KIN33GMAX";s:12:"goods_weight";s:1:"0";s:11:"goods_price";s:5:"42.00";s:12:"goods_number";s:2:"15";s:17:"goods_category_id";s:1:"0";s:14:"goods_brand_id";s:1:"0";s:15:"goods_introduce";s:0:"";s:13:"goods_big_img";s:0:"";s:15:"goods_small_img";s:0:"";s:17:"goods_create_time";s:10:"1241422573";s:15:"goods_last_time";s:10:"1376313927";s:3:"abc";s:0:"";}i:3;a:13:{s:8:"goods_id";s:1:"7";s:10:"goods_name";s:38:"诺基亚N85原装立体声耳机HS-82";s:12:"goods_weight";s:1:"0";s:11:"goods_price";s:6:"100.00";s:12:"goods_number";s:2:"20";s:17:"goods_category_id";s:1:"0";s:14:"goods_brand_id";s:1:"1";s:15:"goods_introduce";s:0:"";s:13:"goods_big_img";s:38:"200905/goods_img/7_G_1241422785856.jpg";s:15:"goods_small_img";s:51:"images/200905/thumb_img/7_thumb_G_1241422785492.jpg";s:17:"goods_create_time";s:10:"1241422785";s:15:"goods_last_time";s:10:"1376309276";s:3:"abc";s:0:"";}i:4;a:13:{s:8:"goods_id";s:1:"8";s:10:"goods_name";s:13:"飞利浦6@6v";s:12:"goods_weight";s:1:"0";s:11:"goods_price";s:7:"1200.00";s:12:"goods_number";s:2:"55";s:17:"goods_category_id";s:1:"3";s:14:"goods_brand_id";s:1:"4";s:15:"goods_introduce";s:1611:"<p align="left">作为一款性价比极高的入门级<font size="3" color="#ff0000"><strong>商务手机</strong></font>，飞利浦<a href="mailto:9@9v">Xenium  9@9v</a>三围大小为105×44×15.8mm，机身重量仅为<strong><font size="3" color="#ff0000">75g</font></strong>，装配了一块低规格1.75英寸128×160像素65000色CSTN显示屏。身正面采用月银色功能键区与屏幕数字键区相分隔，键盘设计较为<font size="3"><strong><font color="#ff0000">别</font><font color="#ff0000">致</font></strong></font>，中部导航键区采用钛金色的“腰带”彰显出浓郁的商务气息。</p>
<p align="left"> </p>
<p align="left">此款手机采用<strong><font size="3" color="#ff0000">触摸屏</font></strong>设计，搭配精致的手写笔，可支持手写中文和英文两个版本。增强的内置系统还能识别潦草字迹，确保在移动中和匆忙时输入文字的识别率。手写指令功能还支持特定图案的瞬间调用，独特的手写记事本功能，可以在触摸屏上随意绘制个性化的图案并进行<strong><font size="3" color="#ff0000">记事提醒</font></strong>，让商务应用更加随意。</p>
<p align="left"> </p>
<p align="left"> 作为入门级为数不多支持<strong><font size="3" color="#ff0000">双卡功能</font></strong>的手机，可以同时插入两张SIM卡，通过菜单随意切换，只需开启漫游自动切换模式，<a href="mailto:9@9V">9@9V</a>在该模式下能够判断网络情况，自动切换适合的手机号。</p>
<p align="left"> </p>
<p align="left"> </p>";s:13:"goods_big_img";s:38:"200905/goods_img/8_G_1241425513055.jpg";s:15:"goods_small_img";s:51:"images/200905/thumb_img/8_thumb_G_1241425513488.jpg";s:17:"goods_create_time";s:10:"1241425512";s:15:"goods_last_time";s:1:"0";s:3:"abc";s:0:"";}i:5;a:13:{s:8:"goods_id";s:1:"9";s:10:"goods_name";s:12:"诺基亚E33";s:12:"goods_weight";s:1:"0";s:11:"goods_price";s:7:"5000.00";s:12:"goods_number";s:1:"4";s:17:"goods_category_id";s:1:"3";s:14:"goods_brand_id";s:1:"1";s:15:"goods_introduce";s:1072:"<p>在机身材质方面，诺基亚E66大量采用金属材质，刨光的金属表面光泽动人，背面的点状效果规则却又不失变化，时尚感总是在不经意间诠释出来，并被人们所感知。E66机身尺寸为<span style="color: rgb(255, 0, 0);"><span style="font-size: larger;"><strong>107.5×49.5×13.6毫米，重量为121克</strong></span></span>，滑盖的造型竟然比E71还要轻一些。</p>
<p> </p>
<div>诺基亚E66机身正面是<span style="color: rgb(255, 0, 0);"><span style="font-size: larger;"><strong>一块2.4英寸1600万色QVGA分辨率（240×320像素）液晶显示屏</strong></span></span>。屏幕上方拥有光线感应元件，能够自适应周 围环境光调节屏幕亮度；屏幕下方是方向功能键区。打开滑盖，可以看到传统的数字键盘，按键的大小、手感、间隔以及键程适中，手感非常舒适。</div>
<div> </div>
<div>诺基亚为E66配备了一颗320万像素自动对焦摄像头，带有LED 闪光灯，支持多种拍照尺寸选择。</div>
<p> </p>";s:13:"goods_big_img";s:45:"images/200905/goods_img/9_G_1241511871574.jpg";s:15:"goods_small_img";s:51:"images/200905/thumb_img/9_thumb_G_1241511871555.jpg";s:17:"goods_create_time";s:10:"1241511871";s:15:"goods_last_time";s:1:"0";s:3:"abc";s:0:"";}i:6;a:13:{s:8:"goods_id";s:2:"10";s:10:"goods_name";s:10:"索爱C706";s:12:"goods_weight";s:1:"0";s:11:"goods_price";s:7:"1500.00";s:12:"goods_number";s:1:"7";s:17:"goods_category_id";s:1:"3";s:14:"goods_brand_id";s:1:"7";s:15:"goods_introduce";s:1889:"<p>C702可以说是一种在外观上复古的产物，不仅延续T系列早期的直板造型，而且在屏幕和键盘的组合分布上都继承了前辈的精髓。C702的机身尺寸为106×48×15.5毫米，重量为105克。此外索尼爱立信为C702融入了<font size="3" color="#ff0000"><strong>三防特性，即防尘、防滑和防水溅</strong></font>，这款新的C702搭载了索尼爱立信经典A200平台，界面布局与W908c、K858c一致，典型的特征就是配备左右软键、中央确定键和通话/挂机键。</p>
<p>索尼爱立信C702配备一块<strong><font size="3" color="#ff0000">2.2英寸26万色TFT液晶显示屏</font></strong>，分辨率为240×320像素(QVGA)，显示效果属于目前主流水准。C702可以说是索尼爱立信首批<strong><font size="3" color="#ff0000">内置GPS模块</font></strong>的 手机产品之一，C702的搜星、定位一气呵成，十分精准，误差大约在10米之内。基本上定位后可以将有效卫星数量控制在4—6颗，可以说可以满足我们的需 要了。C702还提供了“影像定位”功能，配合内置的AGPS全球定位辅助系统，只须启动Geo-Tagging智能影像定位功能，便可将拍摄地点记录在 照片内，方便用户随时查询。</p>
<p> </p>
<p>作为一款Cyber-shot系列影像手机，索尼爱立信C702在拍照功能方面同样有不俗的表现。并且手机内置的<strong><font size="3" color="#ff0000">320万像素摄像头</font></strong>也 同样在拍照功能上也不错的表现。不仅支持自动聚焦和双LED闪光功能，而且还拥有2倍数码变焦、防红眼、Photo fix优画及场景模式等功能。索尼爱立信C702除了配备的是最大光圈为F3.2的4.2毫米镜头之外，该机也如同门中的旗舰C902一样增加了对脸部有 先自动聚焦功能的支持。</p>
<p> </p>";s:13:"goods_big_img";s:46:"images/200905/goods_img/10_G_1242973436141.jpg";s:15:"goods_small_img";s:52:"images/200905/thumb_img/10_thumb_G_1242973436403.jpg";s:17:"goods_create_time";s:10:"1241965622";s:15:"goods_last_time";s:1:"0";s:3:"abc";s:0:"";}}
?>